const products = [
  {
    id: 1,
    name: "AirMax Runner",
    desc: "Lightweight running shoes with breathable mesh.",
    price: 79.99,
    image: "/A3.jpg",
    varient: "shoes",
  },
  {
    id: 2,
    name: "Trail Trek Pro",
    desc: "Durable shoes for outdoor adventures.",
    price: 89.99,
    image: "/A5.jpg",
    varient: "shoes",
  },
  {
    id: 3,
    name: "StreetFlex Sneakers",
    desc: "Stylish sneakers for everyday wear.",
    price: 74.99,
    image: "/A6.jpg",
    varient: "shoes",
  },
  {
    id: 5,
    name: "PowerStep Trainers",
    desc: "Supportive trainers with extra cushioning.",
    price: 82.5,
    image: "/r4.jpg",
    varient: "shoes",
  },
  {
    id: 6,
    name: "Urban Hike",
    desc: "Rugged design perfect for hikes and city walks.",
    price: 92.0,
    image: "/s1.jpg",
    varient: "shoes",
  },
  {
    id: 7,
    name: "ZoomFly XT",
    desc: "High-speed shoes for running performance.",
    price: 99.99,
    image: "/s2.jpg",
    varient: "shoes",
  },
  {
    id: 8,
    name: "Comfy Steps",
    desc: "Everyday comfort shoes for men and women.",
    price: 59.99,
    image: "/s3.png",
    varient: "shoes",
  },
  {
    id: 9,
    name: "SlipOn Ultra",
    desc: "Easy to wear, perfect for casual days.",
    price: 54.0,
    image: "/s4.jpg",
    varient: "shoes",
  },
  {
    id: 10,
    name: "Thunder Run",
    desc: "High grip, waterproof performance shoes.",
    price: 88.75,
    image: "/t2.jpg",
    varient: "shoes",
  },
  {
    id: 11,
    name: "KickMax",
    desc: "Built for sports with advanced foot support.",
    price: 90.0,
    image: "/t3.jpg",
    varient: "shoes",
  },
  {
    id: 12,
    name: "FlexEdge",
    desc: "Bendable soles for agile movements.",
    price: 79.0,
    image: "/t4.jpg",
    varient: "shoes",
  },
  {
    id: 13,
    name: "Summer Dress",
    desc: "Light and breezy floral summer dress.",
    price: 39.99,
    image: "/women1.avif",
    varient: "cloth",
  },
  {
    id: 14,
    name: "Formal Gown",
    desc: "Elegant black dress for formal events.",
    price: 59.99,
    image: "/women2.avif",
    varient: "cloth",
  },
  {
    id: 15,
    name: "Denim Skirt",
    desc: "Trendy mid-length denim skirt.",
    price: 29.99,
    image: "/women3.avif",
    varient: "cloth",
  },
  {
    id: 16,
    name: "Office Blazer",
    desc: "Professional fit blazer for daily workwear.",
    price: 45.0,
    image: "/women4.webp",
    varient: "cloth",
  },
  {
    id: 17,
    name: "Casual Tee",
    desc: "Comfortable cotton tee for everyday wear.",
    price: 19.99,
    image: "/women5.webp",
    varient: "cloth",
  },
  {
    id: 18,
    name: "High Waist Pants",
    desc: "Slim-fit high-waist trousers for women.",
    price: 34.99,
    image: "/women6.avif",
    varient: "cloth",
  },
  {
    id: 19,
    name: "Winter Coat",
    desc: "Wool-blend coat for cold weather.",
    price: 89.99,
    image: "/women7.avif",
    varient: "cloth",
  },
  {
    id: 20,
    name: "Men's Polo",
    desc: "Classic men’s polo shirt with stretch fit.",
    price: 24.99,
    image: "/men1.webp",
    varient: "men",
  },
  {
    id: 21,
    name: "Formal Shirt",
    desc: "Long sleeve dress shirt for men.",
    price: 29.99,
    image: "/men2.webp",
    varient: "men",
  },
  {
    id: 22,
    name: "Casual Tee",
    desc: "Breathable and soft casual T-shirt.",
    price: 18.5,
    image: "/men3.webp",
    varient: "men",
  },
  {
    id: 23,
    name: "Men's Jeans",
    desc: "Comfort fit jeans with stretch material.",
    price: 34.99,
    image: "/men4.webp",
    varient: "men",
  },
  {
    id: 24,
    name: "Hoodie Jacket",
    desc: "Warm and comfortable pullover hoodie.",
    price: 49.99,
    image: "/men5.webp",
    varient: "men",
  },
  {
    id: 25,
    name: "Sport Shorts",
    desc: "Quick-dry athletic shorts for training.",
    price: 21.99,
    image: "/men6.webp",
    varient: "men",
  },
  {
    id: 26,
    name: "Wrist Wraps",
    desc: "Supportive wrist wraps for lifting.",
    price: 15.0,
    image: "/access1.jpg",
    varient: "accessories",
  },
  {
    id: 27,
    name: "Gym Bottle",
    desc: "1L BPA-free fitness water bottle.",
    price: 12.5,
    image: "/access2.jpg",
    varient: "accessories",
  },
  {
    id: 28,
    name: "Headband Pack",
    desc: "Pack of 3 sweat-resistant headbands.",
    price: 9.99,
    image: "/access3.png",
    varient: "accessories",
  },
  {
    id: 29,
    name: "Training Belt",
    desc: "Leather gym belt for back support.",
    price: 34.99,
    image: "/access4.jpeg",
    varient: "accessories",
  },
  {
    id: 30,
    name: "Ankle Support",
    desc: "Compression ankle sleeves for training.",
    price: 13.99,
    image: "/access5.webp",
    varient: "accessories",
  },
  {
    id: 31,
    name: "Resistance Bands",
    desc: "5 levels of resistance for workouts.",
    price: 22.0,
    image: "/access6.webp",
    varient: "accessories",
  },
  {
    id: 32,
    name: "Jump Rope",
    desc: "Speed jump rope with adjustable length.",
    price: 11.99,
    image: "/access7.webp",
    varient: "accessories",
  },
  {
    id: 33,
    name: "Cotton Shirt",
    desc: "Breathable shirt for training or casual wear.",
    price: 25.99,
    image: "/shirt.jpg",
    varient: "shirt",
  },
  {
    id: 34,
    name: "Training Shorts",
    desc: "Sweat-wicking, breathable gym shorts.",
    price: 19.99,
    image: "/short1.jpg",
    varient: "short",
  },
  {
    id: 35,
    name: "Mesh Shorts",
    desc: "Lightweight mesh shorts with inner lining.",
    price: 22.5,
    image: "/short2.jpg",
    varient: "short",
  },
  {
    id: 36,
    name: "Compression Shorts",
    desc: "Tight-fit shorts for running or gym.",
    price: 17.99,
    image: "/short3.jpg",
    varient: "short",
  },
  {
    id: 37,
    name: "Grip Gloves",
    desc: "Anti-slip gloves for heavy lifting.",
    price: 14.99,
    image: "/handgloove.jpg",
    varient: "gloove",
  },
  {
    id: 38,
    name: "DryFit Shirt",
    desc: "Moisture-wicking shirt for intense workouts.",
    price: 27.99,
    image: "/shirt2.jpg",
    varient: "shirt",
  },
  {
    id: 39,
    name: "Muscle Fit Shirt",
    desc: "Slim-fit shirt that highlights your gains.",
    price: 26.5,
    image: "/shirt1.jpg",
    varient: "shirt",
  },
  {
    id: 40,
    name: "Muscle Fit Pants",
    desc: "Tapered athletic pants that hug your legs for a powerful look.",
    price: 36.5,
    image: "/shortw1.jpg",
    varient: "short",
  },
  {
    id: 41,
    name: "Power Stretch Pants",
    desc: "Maximum stretch for deep squats and tough workouts.",
    price: 20.5,
    image: "/shoertw2.jpg",
    varient: "short",
  },
  {
    id: 42,
    name: "Core Fit Joggers",
    desc: "Built for core training and all-day comfort.",
    price: 30.5,
    image: "/shoertw3.webp",
    varient: "short",
  },
  {
    id: 43,
    name: "Flex Grip Pants",
    desc: "Flexible fit with ankle grip for zero distractions.",
    price: 10.5,
    image: "/shoertw4.jpg",
    varient: "short",
  },
  {
    id: 44,
    name: "Iron Fit Bottoms",
    desc: "Strong, structured design that moves with intensity.",
    price: 18.5,
    image: "/shoertw5.jpg",
    varient: "short",
  },
  {
    id: 45,
    name: "Lift Ready Pants",
    desc: "Engineered for lifting days and gym confidence.",
    price: 15.5,
    image: "/shoertw6.jpg",
    varient: "short",
  },
  {
    id: 46,
    name: "Sprint Taper Pants",
    desc: "Tapered cut for speed and sleek motion.",
    price: 26.5,
    image: "/shoertw7.webp",
    varient: "sh0rt",
  },
  {
    id: 47,
    name: "Grind Mode Joggers",
    desc: "Durable pants for your no-excuses grind sessions.",
    price: 29.5,
    image: "/shoertw8.webp",
    varient: "short",
  },
  {
    id: 48,
    name: "Alpha Fit Pants",
    desc: "Elite style with muscle-supporting fabric.",
    price: 26.5,
    image: "/shoertw9.jpg",
    varient: "short",
  },
  {
    id: 49,
    name: "Peak Motion Pants",
    desc: "Designed for top performance in every rep you need.",
    price: 25.5,
    image: "/shoertw10.webp",
    varient: "short",
  },

  {
    id: 50,
    name: "Lift Luxe Top",
    desc: "Premium fit for lifting queens.",
    price: 36.5,
    image: "/topw1.jpg",
    varient: "top",
  },
  {
    id: 51,
    name: "Active Curve Tank",
    desc: "Designed to flatter and move with you anywhere.",
    price: 26.5,
    image: "/topw2.jpg",
    varient: "top",
  },
  {
    id: 52,
    name: "Sweat Sculpt Tee",
    desc: "Wicks sweat, shapes beautifully, and feels light.",
    price: 22.5,
    image: "/topw3.jpg",
    varient: "top",
  },
  {
    id: 53,
    name: "Glow Fit Crop",
    desc: "Breathable cropped top that shows strength and style.",
    price: 18.5,
    image: "/topw4.jpg",
    varient: "top",
  },
  {
    id: 54,
    name: "Power Babe Tank",
    desc: "Lightweight and fierce — for unstoppable workouts.",
    price: 34.5,
    image: "/topw5.jpg",
    varient: "top",
  },
  {
    id: 55,
    name: "Flex Femme Tee",
    desc: "Soft stretch fabric built for strong women proper use.",
    price: 56.5,
    image: "/topw6.jpg",
    varient: "top",
  },
  {
    id: 56,
    name: "Sculpt Fit Top",
    desc: "Hugs your curves while supporting every move.",
    price: 19.5,
    image: "/topw7.jpg",
    varient: "top",
  },
  {
    id: 57,
    name: "VelociRun",
    desc: "Speed meets stability.",
    price: 18.5,
    image: "/shoe1.jpg",
    varient: "shoes",
  },
  {
    id: 58,
    name: "AirThrust",
    desc: "Power in every stride.",
    price: 19.5,
    image: "/shoe2.webp",
    varient: "shoes",
  },
  {
    id: 59,
    name: "NovaStep",
    desc: "Shine bright every step.",
    price: 20.5,
    image: "/shoe3.jpg",
    varient: "shoes",
  },
  {
    id: 60,
    name: "GripCore",
    desc: "Built tough for trails.",
    price: 30.5,
    image: "/shoe4.jpg",
    varient: "shoes",
  },
  {
    id: 61,
    name: "UrbanVault",
    desc: "Street-ready comfort.",
    price: 15.5,
    image: "/shoe5.jpg",
    varient: "shoes",
  },
  {
    id: 62,
    name: "StrideFlex",
    desc: "Lightweight sporty kicks.",
    price: 18.5,
    image: "/shoe6.webp",
    varient: "shoes",
  },
  {
    id: 63,
    image: "/gym1.jpg",
    name: "BRAND/TYPE",
    desc: "Name and characterics",
    price: "74,95 $",
    discount: "121,00 $",
    list: "(45)",
    varient: "Accesories",
  },
  {
    id: 64,
    image: "/gym2.jpg",
    name: "BRAND/TYPE",
    desc: "Name and characterics",
    price: "74,95 $",
    discount: " 121,00 $",
    list: "(45)",
    varient: "Accesories",
  },
  {
    id: 65,
    image: "/gym3.jpg",
    name: "BRAND/TYPE",
    desc: "Name and characterics",
    price: "74,95 $",
    discount: " 121,00 $",
    list: "(45)",
    varient: "Accesories",
  },
  {
    id: 66,
    image: "/gym4.jpg",
    name: "BRAND/TYPE",
    desc: "Name and characterics",
    price: "74,95 $",
    discount: " 121,00 $",
    list: "(45)",
    varient: "Accesories",
  },
  {
    id: 67,
    image: "/gym5.jpg",
    name: "BRAND/TYPE",
    desc: "Name and characterics",
    price: "74,95 $",
    discount: " 121,00 $",
    list: "(45)",
    varient: "Accesories",
  },
  {
    id: 68,
    image: "/gym6.jpg",
    name: "BRAND/TYPE",
    desc: "Name and characterics",
    price: "74,95 $",
    discount: " 121,00 $",
    list: "(45)",
    varient: "Accesories",
  },
];

export default products;
